### ISSUE TITLE
Remove Dats from memory after a period

### ISSUE THREAD

**Issue by pfrazee** [pfrazee/dat-gateway#1]

**Comment by garbados** [comment]
I have a fork of this project that implements a cache using the [lru-cache](https://www.npmjs.com/package/lru-cache) module: https://github.com/garbados/dat-gateway/pull/3

Merging the fork would imply some significant changes to the codebase, but it would implement a cache.

**Comment by garbados** [comment]
Now that the cache has been [merged](https://github.com/pfrazee/dat-gateway/commit/c9d2fa2001a25f49598fb14eb6ef4678316ca5af), should this issue be closed?

**Comment by pfrazee** [comment]
Yep!
